---
namespace: Titanium.Process.Process.getEnvironment
type: method
description: 
since: 0.5.0
platforms: ['android', 'iphone']
returns: String|Object
parameters: 
    - [String, key, an environment key]
