---
namespace: Titanium.Process.Process.setEnvironment
type: method
description: Set an environment variable for this process
since: 0.5.0
platforms: ['android', 'iphone']
returns: String
parameters: 
    - [String, key, an environment key]
    - [String, value, the value]
