---
namespace: Titanium.Filesystem.getApplicationDataDirectory
type: method
description: Returns the data directory of the application
since: 0.8.0
platforms: ['osx', 'linux', 'win32']
returns: FileSystem.File
parameters: []
