---
namespace: Titanium.Filesystem.getApplicationDataDirectory
type: function
description: Returns the data directory of the application
since: 0.8.0
platforms: ['osx', 'linux', 'win32']
returns: Filesystem.File
parameters: []
