---
namespace: Titanium.Filesystem.getApplicationDirectory
type: method
description: Returns the directory where the application resides
since: 0.8.0
platforms: ['osx', 'linux', 'win32']
returns: Filesystem.File
parameters: []
